DROP TABLE IF EXISTS orders CASCADE;

CREATE TABLE IF NOT EXISTS orders (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
    order_number VARCHAR(255) NOT NULL,
	status VARCHAR(255) NOT NULL,
	created_at TIMESTAMP NOT NULL
);

-- INSERT INTO Book (title, quantity)
-- VALUES ('Java The Complete Reference 9th Edition', 40),
--        ('Design Patterns: Elements of Reusable Object-Oriented Software', 30),
--        ('Grokking Algorithms', 25),
--        ('War and Peace', 30),
--        ('Adventures of Huckleberry Finn', 50),
--        ('Dune', 45);

